slack:
  host: https://slack.com
  token:
    verification: thisisagoodtoken
    bot: iamthebestbot

bot:
  userId: bestbot

logging:
  level:
    io.holyguacamole.bot.controller: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug

season:
  reset:
    month: 01
    day: 01


spring:
  thymeleaf:
    cache: false

milecado:
  next: 10
  channel: CHANNELID
